Repository open-cluster-management-io/policy-collection, pull requests merged in 2020-10, with the labels that each got.

#28 move etcd encyrption policy to stable
  community/README.md
  stable/CM-Configuration-Management/policy-etcdencryption.yaml
  stable/README.md
Labels: approved

#30 Update policy-imagemanifestvuln.yaml
  stable/SI-System-and-Information-Integrity/policy-imagemanifestvuln.yaml
Labels: approved, lgtm

#31 Gatekeeper policies from Red Hat CoP
  community/CM-Configuration-Management/policy-gatekeeper-container-image-latest.yaml
  community/CM-Configuration-Management/policy-gatekeeper-container-livenessprobenotset.yaml
  community/CM-Configuration-Management/policy-gatekeeper-container-readinessprobenotset.yaml
  community/README.md
Labels: approved, lgtm

#26 add a sample ocp certificate policy, tuning still needed
  community/README.md
  community/SC-System-and-Communications-Protection/policy-ocp4-certs.yaml
Labels: approved, lgtm

#35 Update README.md
  README.md
Labels: lgtm

#32 create a least privilege policy that looks for a role using wildcards
  community/AC-Access-Control/policy-roles-no-wildcards.yaml
  community/README.md
Labels: approved

#36 Add policy to install the Compliance Operator
  community/CA-Security-Assessment-and-Authorization/policy-compliance-operator-install-upstream.yaml
  community/README.md
Labels: approved, lgtm

#37 Add policy to scan clusters with the E8 benchmark
  community/CM-Configuration-Management/policy-compliance-operator-e8-scan.yaml
  community/README.md
Labels: approved, lgtm

#40 Update community README table
  community/README.md
Labels: approved, lgtm

#39 Adding new community configuration management policies (cnf)
  community/CM-Configuration-Management/policy-label-worker-nodes.yaml
  community/CM-Configuration-Management/policy-pao-operator.yaml
  community/CM-Configuration-Management/policy-ptp-operator.yaml
  community/CM-Configuration-Management/policy-sriov-operator.yaml
  community/README.md
Labels: approved, lgtm

#41 Update stable table
  stable/README.md
Labels: approved, lgtm

#43 fix policy link and add missing descirption
  community/README.md
Labels: approved, lgtm

#38 Add etcd backup policy using default storage class
  community/CM-Configuration-Management/policy-etcd-backup.yaml
  community/README.md
Labels: lgtm

#42 Provide policy that installs the official compliance operator
  community/CA-Security-Assessment-and-Authorization/policy-compliance-operator-install.yaml
  community/README.md
Labels: approved, lgtm

#44 Update policy-etcd-backup.yaml
  community/CM-Configuration-Management/policy-etcd-backup.yaml
Labels: approved, lgtm
