Repository open-cluster-management-io/policy-collection, pull requests merged in 2020-07, with the labels that each got.

#2 add policies organized by NIST SP 800-53
  OWNERS
  README.md
  community/CM-Configuration-Management/policy-trusted-container.yaml
  community/README.md
  docs/CONTRIBUTING.md
  stable/AC-Access-Control/policy-limitclusteradmin.yaml
  stable/AC-Access-Control/policy-role.yaml
  stable/AC-Access-Control/policy-rolebinding.yaml
  stable/CM-Configuration-Management/policy-limitmemory.yaml
  stable/CM-Configuration-Management/policy-namespace.yaml
  stable/CM-Configuration-Management/policy-pod.yaml
  stable/README.md
  stable/SC-System-and-Communications-Protection/policy-certificate.yaml
  stable/SI-System-and-Information-Integrity/policy-imagemanifestvuln.yaml
  stable/SI-System-and-Information-Integrity/policy-psp.yaml
  stable/SI-System-and-Information-Integrity/policy-scc.yaml
Labels: lgtm

#3 update policies
  stable/AC-Access-Control/policy-limitclusteradmin.yaml
  stable/AC-Access-Control/policy-role.yaml
  stable/AC-Access-Control/policy-rolebinding.yaml
  stable/CM-Configuration-Management/policy-limitmemory.yaml
  stable/CM-Configuration-Management/policy-namespace.yaml
  stable/CM-Configuration-Management/policy-pod.yaml
  stable/SC-System-and-Communications-Protection/policy-certificate.yaml
  stable/SI-System-and-Information-Integrity/policy-imagemanifestvuln.yaml
  stable/SI-System-and-Information-Integrity/policy-psp.yaml
  stable/SI-System-and-Information-Integrity/policy-scc.yaml
Labels: approved

#4 Add Falco enforcement policy
  community/README.md
  community/SI-System-and-Information-Integrity/policy-falco.yaml
Labels: approved, lgtm

#6 Add Sysdig Agent enforcement policy
  community/README.md
  community/SI-System-and-Information-Integrity/policy-sysdig.yaml
Labels: approved, lgtm

#5 Create opa-configmap.yaml
  community/CM-Configuration-Management/policy-opa-sample.yaml
  community/README.md
Labels: approved, lgtm
