Repository open-cluster-management-io/policy-collection, pull requests merged in 2021-04, with the labels that each got.

#103 added black duck policy for cluster management
  community/README.md
  community/SI-System-and-Information-Integrity/policy-blackduck.yaml
Labels: approved, lgtm

#104 exclude more openshift ns
  community/CM-Configuration-Management/policy-gatekeeper-config-exclude-namespaces.yaml
Labels: approved, lgtm

#106 update OWNERS and nginx image
  OWNERS
  stable/CM-Configuration-Management/policy-pod.yaml
Labels: approved, lgtm

#105 Add DCO
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: approved, dco-signoff: yes, lgtm

#107 get the sysdig/falco policies working on new openshift releases
  community/CM-Configuration-Management/policy-kernel-devel.yaml
  community/README.md
  community/SI-System-and-Information-Integrity/policy-falco.yaml
  community/SI-System-and-Information-Integrity/policy-sysdig.yaml
Labels: approved, dco-signoff: no, lgtm
