Repository open-cluster-management-io/policy-collection, pull requests merged in 2021-08, with the labels that each got.

#135 Adds policy for installing LSO
  community/CM-Configuration-Management/policy-odf-lso.yaml
  community/README.md
Labels: approved, dco-signoff: yes, lgtm

#133 added openshift-config namespace to the included namespaces
  community/SC-System-and-Communications-Protection/policy-ocp4-certs.yaml
Labels: approved, dco-signoff: no, lgtm

#137 add a sample for installing the acs secure cluster services
  community/CM-Configuration-Management/policy-acs-operator-clusters.yaml
  community/README.md
Labels: approved, dco-signoff: no, lgtm

#138 add some blogs missing from the readme
  README.md
  blogs/README.md
Labels: lgtm, approved, dco-signoff: yes

#140 Add ApplyTo section to Assign gatekeeper policy
  community/CM-Configuration-Management/policy-gatekeeper-image-pull-policy.yaml
Labels: lgtm, approved, dco-signoff: yes

#139 Add links to prerequisite instructions for this policy
  community/README.md
Labels: lgtm, approved, dco-signoff: no

#141 Sync rate
  deploy/README.md
  deploy/channel.yaml
  deploy/channel_template.json
  deploy/deploy.sh
Labels: lgtm, approved, dco-signoff: yes

#142 Update README.md
  blogs/README.md
Labels: lgtm, dco-signoff: yes

#143 added policies
  community/CM-Configuration-Management/policy-ansible-awx-operator.yaml
  community/CM-Configuration-Management/policy-argocd-kubernetes.yaml
  community/CM-Configuration-Management/policy-cluster-logforwarder-templatized.yaml
  community/CM-Configuration-Management/policy-cluster-network-sample.yaml
  community/CM-Configuration-Management/policy-custom-catalog.yaml
  community/CM-Configuration-Management/policy-install-external-secrets.yaml
  community/CM-Configuration-Management/policy-install-kyverno.yaml
  community/CM-Configuration-Management/policy-kyverno-sample.yaml
  community/CM-Configuration-Management/policy-observability-allowlist.yaml
  community/CM-Configuration-Management/policy-ocs-setup.yaml
  community/CM-Configuration-Management/policy-odf-lso.yaml
  community/CM-Configuration-Management/policy-odf.yaml
  community/CM-Configuration-Management/policy-upgrade-openshift-cluster.yaml
  community/README.md
  community/SC-System-and-Communications-Protection/policy-checkclusteroperator.yaml
Labels: lgtm, approved, dco-signoff: yes

#144 Adding the Ansible Integration blog
  blogs/README.md
Labels: lgtm, approved, dco-signoff: yes
