Repository open-cluster-management-io/policy-collection, pull requests merged in 2021-10, with the labels that each got.

#161 fix pao operator so the new version is installed
  community/CM-Configuration-Management/policy-pao-operator.yaml
Labels: lgtm, approved, dco-signoff: yes

#158 gatekeeper-operator v0.2.0
  community/CM-Configuration-Management/policy-gatekeeper-operator.yaml
  stable/CM-Configuration-Management/policy-gatekeeper-operator-downstream.yaml
Labels: lgtm, approved

#165 Update README.md
  blogs/README.md
Labels: lgtm, approved, dco-signoff: no

#173 Fix kyverno policy
  community/CM-Configuration-Management/policy-install-kyverno.yaml
  community/CM-Configuration-Management/policy-oauth-config.yaml
Labels: lgtm, approved, dco-signoff: yes
